# Generated by Django 5.2.16 on 2026-08-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('member', 'Сотрудник'), ('manager', 'Руководитель')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['display_name', 'username'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'manager')), fields=('role',), name='backlog_single_manager')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('reporter', models.CharField(blank=True, max_length=200)),
                ('direction', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('waiting', 'Ожидает оценки'), ('p0', 'P0 — критично'), ('p1', 'P1 — высокий'), ('p2', 'P2 — средний'), ('p3', 'P3 — низкий'), ('stop', 'Стоп')], default='waiting', max_length=20)),
                ('status', models.CharField(choices=[('idea', 'Идея'), ('new', 'Новая'), ('planned', 'Запланирована'), ('in_progress', 'В работе'), ('blocked', 'Заблокирована'), ('review', 'На проверке'), ('done', 'Готово'), ('cancelled', 'Отменена')], default='new', max_length=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('blockers', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('materials_url', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='tasks.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='tasks.employee')),
            ],
            options={
                'ordering': ['priority', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_changes', to='tasks.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
