# Generated by Django 5.2.16 on 2026-08-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
