# Generated by Django 5.2.16 on 2026-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_source_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
