# Generated by Django 5.2.16 on 2026-08-14 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completion_comment_task_completion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TelegramLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_requests', to='tasks.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
