# Generated by Django 5.2.16 on 2026-08-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_task_watchers', to='tasks.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_watcher_links', to='tasks.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_links', to='tasks.task')),
            ],
            options={
                'ordering': ['employee__display_name', 'employee__username', 'id'],
                'constraints': [models.UniqueConstraint(fields=('task', 'employee'), name='backlog_unique_task_watcher')],
            },
        ),
    ]
