# Generated by Django 5.2.16 on 2026-08-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskwatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramoutbox',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Назначена'), ('status_changed', 'Изменён статус'), ('completed', 'Завершена'), ('overdue', 'Просрочена'), ('commented', 'Новый комментарий')], max_length=30),
        ),
    ]
