# Generated by Django 5.2.16 on 2026-08-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_telegramoutbox_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTaskFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('my', 'Мои задачи'), ('all', 'Все задачи')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_task_filters', to='tasks.employee')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'scope', 'name'), name='backlog_unique_saved_filter_name')],
            },
        ),
    ]
